AWSTemplateFormatVersion: '2010-09-09'
Description: >
  digitized-image-notifications

  Handles notifications for validation and packaging of incoming digitized still image and textual assets.

Parameters:
  ApplicationEnvironment:
    Type: String
    Description: The environment in which the application should be deployed.
    AllowedValues:
      - dev
      - prod
  ApplicationName:
    Type: String
    Description: The name of the application to be deployed.
  TeamsUrl:
    Type: String
    Description: URL for a Teams channel webhook.

Resources:
  HandleDigitizedImageNotificationsRole:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Description: !Sub 'Allows ${ApplicationName} lambda to be executed successfully.'
      Policies:
        - PolicyName: DigitizedImageParameterStorePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 
                  - 'ssm:GetParametersByPath*'
                Resource: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${ApplicationEnvironment}/${ApplicationName}*'
        - PolicyName: DigitizedImageLogPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource:
                  - !GetAtt NotificationsLogGroup.Arn
  
  DigitizedImageEventsTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: digitized-image-events

  TeamsUrlParameter:
    Type: AWS::SSM::Parameter
    Properties: 
      Description: URL for Teams Channel webhook.
      Name: !Sub /${ApplicationEnvironment}/${ApplicationName}/TEAMS_URL
      Tags: 
        Environment: !Ref ApplicationEnvironment
        Application: !Ref ApplicationName
      Type: String
      Value: !Ref TeamsUrl

  HandleDigitizedImageNotificationsFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Sub 'rac-${ApplicationEnvironment}-lambda'
        S3Key: !Sub '${ApplicationName}.zip'
      FunctionName: !Ref ApplicationName
      Handler: handle_digitized_image_notifications.lambda_handler
      Role: !GetAtt HandleDigitizedImageNotificationsRole.Arn
      Runtime: python3.11
      Timeout: 30
      Environment:
        Variables:
          ENV: !Ref ApplicationEnvironment
          APP_CONFIG_PATH: !Ref ApplicationName
      Tags:
        - Key: Environment
          Value: !Ref ApplicationEnvironment
        - Key: Application
          Value: !Ref ApplicationName
      Architectures:
        - x86_64

  NotificationsLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${ApplicationName}"
      RetentionInDays: 90
  
  HandleDigitizedImageNotificationsFunctionDigitizedImageEventsPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref HandleDigitizedImageNotificationsFunction
      Principal: sns.amazonaws.com
      SourceArn: !Ref DigitizedImageEventsTopic

  HandleDigitizedImageNotificationsFunctionDigitizedImageEventsTravisEcRPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref HandleDigitizedImageNotificationsFunction
      Action: "lambda:UpdateFunctionCode"
      Principal: "arn:aws:iam::817658541382:user/TravisECR"
  
  HandleDigitizedImageNotificationsFunctionDigitizedImageEvents:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !GetAtt HandleDigitizedImageNotificationsFunction.Arn
      Protocol: lambda
      TopicArn: !Ref DigitizedImageEventsTopic

Outputs:
  HandleDigitizedImageNotificationsFunction:
    Description: 'Handle Digitized Image Notifications Lambda Function ARN'
    Value: !GetAtt HandleDigitizedImageNotificationsFunction.Arn
  DigitizedImageEventsTopic:
    Description: 'Digitized Image Events SNS Topic ARN'
    Value: !Ref DigitizedImageEventsTopic
    Export:
      Name:
        DigitizedImage-SNSTopicArn