AWSTemplateFormatVersion: '2010-09-09'
Description: >
  digitized-image-packaging

  Handles packaging of incoming digitized still image and textual assets.

Parameters:
  ContainerAccountId:
    Type: String
    Description: Account ID under which container repository is located.
    Default: "817658541382"
  ApplicationEnvironment:
    Type: String
    Description: Environment in which application should be deployed.
    AllowedValues:
      - dev
      - prod
  ApplicationName:
    Type: String
    Description: Name of the application to be deployed.
  EfsId:
    Type: String
    Description: Identifier for temporary storage EFS.
  EfsAccessPointId:
    Type: String
    Description: Identifier for temporary storage EFS access point.
  EfsRootPath:
    Type: String
    Description: Root path at which EFS is mounted.
  StoragePath:
    Type: String
    Description: Location in EFS mount at which source files are stored.
  TemporaryPath:
    Type: String
    Description: Location in EFS mount at which files are unpacked.
  DestinationBucketName:
    Type: String
    Description: Name of S3 bucket to which packaged files should be delivered.
  ArchivesSpaceRepo:
    Type: String
    Description: ArchivesSpace repository identifier.
  ArchivesSpaceBaseUrl:
    Type: String
    Description: ArchivesSpace base URL.
  ArchivesSpaceUsername:
    Type: String
    Description: ArchivesSpace username.
  ArchivesSpacePassword:
    Type: String
    Description: ArchivesSpace password.

Resources:  
  ArchivesSpaceRepoParameter:
    Type: AWS::SSM::Parameter
    Properties: 
      Description: ArchivesSpace repository identifier.
      Name: !Sub /${ApplicationEnvironment}/${ApplicationName}/AS_REPO
      Tags: 
        Environment: !Ref ApplicationEnvironment
        Application: !Ref ApplicationName
      Type: String
      Value: !Ref ArchivesSpaceRepo
  ArchivesSpaceBaseUrlParameter:
    Type: AWS::SSM::Parameter
    Properties: 
      Description: ArchivesSpace base URL.
      Name: !Sub /${ApplicationEnvironment}/${ApplicationName}/AS_BASEURL
      Tags: 
        Environment: !Ref ApplicationEnvironment
        Application: !Ref ApplicationName
      Type: String
      Value: !Ref ArchivesSpaceBaseUrl
  ArchivesSpaceUsernameParameter:
    Type: AWS::SSM::Parameter
    Properties: 
      Description: ArchivesSpace username.
      Name: !Sub /${ApplicationEnvironment}/${ApplicationName}/AS_USERNAME
      Tags: 
        Environment: !Ref ApplicationEnvironment
        Application: !Ref ApplicationName
      Type: String
      Value: !Ref ArchivesSpaceUsername
  ArchivesSpacePasswordParameter:
    Type: AWS::SSM::Parameter
    Properties: 
      Description: ArchivesSpace password.
      Name: !Sub /${ApplicationEnvironment}/${ApplicationName}/AS_PASSWORD
      Tags: 
        Environment: !Ref ApplicationEnvironment
        Application: !Ref ApplicationName
      Type: String
      Value: !Ref ArchivesSpacePassword

  ECSTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      Policies:
        - PolicyName: CreateLogGroupPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 
                  - 'logs:CreateLogGroup'
                Resource: 
                  - '*'

  DigitizedImagePackagingUser:
    Type: AWS::IAM::User

  DigitizedImagePackagingUserAccessKey:
    Type: AWS::IAM::AccessKey
    Properties: 
      UserName: !Ref DigitizedImagePackagingUser

  DigitizedImagePackagingRole:
    Type: AWS::IAM::Role
    Properties: 
      RoleName: digitized-image-packaging-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - !GetAtt DigitizedImagePackagingUser.Arn
            Action:
              - 'sts:AssumeRole'
      Description: !Sub 'Allows management of S3 assets and creation of SNS messages.'
      Policies:
        - PolicyName: DigitizedImagePackagingS3ObjectPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 
                  - 's3:PutObject'
                  - 's3:CreateMultipartUpload'
                Resource: 
                  - !Sub 'arn:aws:s3:::${DestinationBucketName}/*'
        - PolicyName: DigitizedImagePackagingSNSPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 'sns:Publish'
                Resource: !ImportValue DigitizedImage-SNSTopicArn
        - PolicyName: DigitizedImagePackagingSSMPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 
                  - 'ssm:GetParametersByPath'
                Resource:
                  - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${ApplicationEnvironment}/${ApplicationName}

  PackagingLogGroup:
    Type: AWS::Logs::LogGroup
    Properties: 
      LogGroupName: !Sub "/digitized_image/ecs/${ApplicationName}"
      RetentionInDays: 90
  
  PackagingECSTask:
    Type: AWS::ECS::TaskDefinition
    Properties: 
      Cpu: "1024"
      Memory: "3072"
      ContainerDefinitions: 
        - Name: !Ref ApplicationName
          Image: !Sub "${ContainerAccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ApplicationName}:latest"
          Essential: true
          Environment:
            - Name: ENV
              Value: !Ref ApplicationEnvironment
            - Name: APP_CONFIG_PATH
              Value: !Ref ApplicationName
            - Name: AWS_ACCESS_KEY_ID
              Value: !Ref DigitizedImagePackagingUserAccessKey
            - Name: AWS_SECRET_ACCESS_KEY
              Value: !GetAtt DigitizedImagePackagingUserAccessKey.SecretAccessKey
            - Name: AWS_REGION
              Value: !Ref AWS::Region
            - Name: AWS_ROLE_ARN
              Value: !GetAtt DigitizedImagePackagingRole.Arn
            - Name: SOURCE_DIR
              Value: !Sub '${EfsRootPath}/${StoragePath}'
            - Name: TMP_DIR
              Value: !Sub '${EfsRootPath}/${TemporaryPath}'
            - Name: AWS_DESTINATION_BUCKET
              Value: !Ref DestinationBucketName
            - Name: AWS_SNS_TOPIC
              Value: !ImportValue DigitizedImage-SNSTopicArn      
          MountPoints:
            - SourceVolume: efs
              ContainerPath: !Ref EfsRootPath
              ReadOnly: false
          LogConfiguration:
            LogDriver: awslogs
            Options:
              "awslogs-group": !Ref PackagingLogGroup
              "awslogs-region": !Ref AWS::Region
              "awslogs-stream-prefix": "ecs"
      ExecutionRoleArn: !GetAtt ECSTaskExecutionRole.Arn
      Family: !Ref ApplicationName
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      RuntimePlatform:
        CpuArchitecture: X86_64
        OperatingSystemFamily: LINUX
      Volumes: 
        - Name: efs
          EFSVolumeConfiguration:
            FilesystemId: !Ref EfsId
            RootDirectory: /
            TransitEncryption: ENABLED
            AuthorizationConfig:
              AccessPointId: !Ref EfsAccessPointId
              IAM: DISABLED

Outputs:
  PackagingECSTask:
    Description: Packaging ECS Task Definition ARN
    Value: !Ref PackagingECSTask