AWSTemplateFormatVersion: '2010-09-09'
Description: >
  digitized-image-validation

  Handles validation of incoming digitized still image and textual assets.

Parameters:
  ContainerAccountId:
    Type: String
    Description: Account ID under which container repository is located.
    Default: '817658541382'
  ApplicationEnvironment:
    Type: String
    Description: Environment in which application should be deployed.
    AllowedValues:
      - dev
      - prod
  ApplicationName:
    Type: String
    Description: Name of the application to be deployed.
  DestinationBucketName:
    Type: String
    Description: Name of bucket to which valid files are moved after processing.
  EbsStorageMountPath:
    Type: String
    Description: Mount path for EBS storage
  Workload:
    Type: String
    Description: Name of workload for this stack.

Resources:
  ECSTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      Tags:
        - Key: Environment
          Value: !Ref ApplicationEnvironment
        - Key: Application
          Value: !Ref ApplicationName
        - Key: Workload
          Value: !Ref Workload
        - Key: WorkloadType
          Value: processing
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: LogPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: 
                  - !GetAtt ValidationLogGroup.Arn
        - PolicyName: EcrPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 
                  - 'ecr:BatchCheckLayerAvailability'
                  - 'ecr:GetDownloadUrlForLayer'
                  - 'ecr:BatchGetImage'
                Resource: 
                  - !Sub arn:${AWS::Partition}:ecr:${AWS::Region}:${ContainerAccountId}:repository/${ApplicationName}
              - Effect: Allow
                Action:
                  - 'ecr:GetAuthorizationToken'
                Resource: "*"
        - PolicyName: SSMPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'ssm:GetParameters'
                Resource:
                  - !Sub arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${ApplicationEnvironment}/${ApplicationName}/*

  DigitizedImageValidationUser:
    Type: AWS::IAM::User
    Properties:
      Tags:
        - Key: Environment
          Value: !Ref ApplicationEnvironment
        - Key: Application
          Value: !Ref ApplicationName
        - Key: Workload
          Value: !Ref Workload
        - Key: WorkloadType
          Value: processing

  DigitizedImageValidationUserAccessKey:
    Type: AWS::IAM::AccessKey
    Properties: 
      UserName: !Ref DigitizedImageValidationUser

  DigitizedImageValidationUserIdParameter:
    Type: AWS::SSM::Parameter
    Properties: 
      Description: Secret Access Key ID for DigitizedImageValidationUser.
      Name: !Sub /${ApplicationEnvironment}/${ApplicationName}/AWS_ACCESS_KEY_ID
      Tags: 
        Environment: !Ref ApplicationEnvironment
        Application: !Ref ApplicationName
        Workload: !Ref Workload
        WorkloadType: processing
      Type: String
      Value: !Ref DigitizedImageValidationUserAccessKey

  DigitizedImageValidationUserKeyParameter:
    Type: AWS::SSM::Parameter
    Properties: 
      Description: Secret Access Key for DigitizedImageValidationUser.
      Name: !Sub /${ApplicationEnvironment}/${ApplicationName}/AWS_SECRET_ACCESS_KEY
      Tags: 
        Environment: !Ref ApplicationEnvironment
        Application: !Ref ApplicationName
        Workload: !Ref Workload
        WorkloadType: processing
      Type: String
      Value: !GetAtt DigitizedImageValidationUserAccessKey.SecretAccessKey

  DigitizedImageValidationS3Role:
    Type: AWS::IAM::Role
    Properties: 
      Tags:
        - Key: Environment
          Value: !Ref ApplicationEnvironment
        - Key: Application
          Value: !Ref ApplicationName
        - Key: Workload
          Value: !Ref Workload
        - Key: WorkloadType
          Value: processing
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: 
              AWS:
                - !GetAtt DigitizedImageValidationUser.Arn
            Action:
              - 'sts:AssumeRole'
      Description: 'Allows management of S3 assets.'
      Policies:
        - PolicyName: DigitizedImageValidationS3BucketPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 
                  - 's3:ListBucket'
                Resource: 
                  - !Sub arn:${AWS::Partition}:s3:::rac-${ApplicationEnvironment}-image-upload
                  - !Sub arn:${AWS::Partition}:s3:::${DestinationBucketName}
        - PolicyName: DigitizedImageValidationS3ObjectPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 
                  - 's3:GetObject'
                  - 's3:DeleteObject'
                  - 's3:PutObject'
                Resource: 
                  - !Sub arn:${AWS::Partition}:s3:::rac-${ApplicationEnvironment}-image-upload/*
                  - !Sub arn:${AWS::Partition}:s3:::${DestinationBucketName}/*
  
  DigitizedImageValidationSnsRole:
    Type: AWS::IAM::Role
    Properties: 
      Tags:
        - Key: Environment
          Value: !Ref ApplicationEnvironment
        - Key: Application
          Value: !Ref ApplicationName
        - Key: Workload
          Value: !Ref Workload
        - Key: WorkloadType
          Value: processing
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: 
              AWS:
                - !GetAtt DigitizedImageValidationUser.Arn
            Action:
              - 'sts:AssumeRole'
      Description: 'Allows creation of SNS messages.'
      Policies:      
        - PolicyName: DigitizedImageValidationSNSPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 'sns:Publish'
                Resource: !ImportValue DigitizedImage-SNSTopicArn

  ValidationLogGroup:
    Type: AWS::Logs::LogGroup
    Properties: 
      LogGroupName: !Sub "/digitized_image/ecs/${ApplicationName}"
      RetentionInDays: 90
      Tags:
        - Key: Environment
          Value: !Ref ApplicationEnvironment
        - Key: Application
          Value: !Ref ApplicationName
        - Key: Workload
          Value: !Ref Workload
        - Key: WorkloadType
          Value: processing

  ValidationECSTask:
    Type: AWS::ECS::TaskDefinition
    Properties: 
      Cpu: "1024"
      Memory: "3072"
      ContainerDefinitions: 
        - Name: !Ref ApplicationName
          Image: !Sub "${ContainerAccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ApplicationName}:${ApplicationEnvironment}"
          Essential: true
          Environment:
            - Name: AWS_S3_ROLE_ARN
              Value: !GetAtt DigitizedImageValidationS3Role.Arn
            - Name: AWS_SNS_ROLE_ARN
              Value: !GetAtt DigitizedImageValidationSnsRole.Arn
            - Name: ENV
              Value: !Ref ApplicationEnvironment
            - Name: APP_CONFIG_PATH
              Value: !Ref ApplicationName
            - Name: DESTINATION_BUCKET
              Value: !Ref DestinationBucketName
            - Name: AWS_REGION_NAME
              Value: !Ref AWS::Region
            - Name: AWS_SNS_TOPIC
              Value: !ImportValue DigitizedImage-SNSTopicArn
            - Name: TMP_DIR
              Value: !Ref EbsStorageMountPath
          MountPoints:
            - SourceVolume: ebs
              ContainerPath: !Ref EbsStorageMountPath
              ReadOnly: false
          ReadonlyRootFilesystem: true
          Secrets:
            - Name: AWS_ACCESS_KEY_ID
              ValueFrom: !Sub 'arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:parameter${DigitizedImageValidationUserIdParameter}'
            - Name: AWS_SECRET_ACCESS_KEY
              ValueFrom: !Sub 'arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:parameter${DigitizedImageValidationUserKeyParameter}'
          LogConfiguration:
            LogDriver: awslogs
            Options:
              "awslogs-group": !Ref ValidationLogGroup
              "awslogs-region": "us-east-1"
              "awslogs-stream-prefix": "ecs"
      ExecutionRoleArn: !GetAtt ECSTaskExecutionRole.Arn
      Family: !Ref ApplicationName
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      RuntimePlatform:
        CpuArchitecture: X86_64
        OperatingSystemFamily: LINUX
      Tags:
        - Key: Environment
          Value: !Ref ApplicationEnvironment
        - Key: Application
          Value: !Ref ApplicationName
        - Key: Workload
          Value: !Ref Workload
        - Key: WorkloadType
          Value: processing
      Volumes: 
        - Name: ebs
          ConfiguredAtLaunch: true

Outputs:
  ValidationECSTask:
    Description: "Validation ECS Task Definition ARN"
    Value: !Ref ValidationECSTask