AWSTemplateFormatVersion: '2010-09-09'
Description: >
  digitized-image-trigger

  Handles notifications for validation and packaging of incoming digitized still image and textual assets.

Parameters:
  ApplicationEnvironment:
    Type: String
    Description: Environment in which the application should be deployed.
    AllowedValues:
      - dev
      - prod
  ApplicationName:
    Type: String
    Description: Name of the application to be deployed.
  ECSClusterName:
    Type: String
    Description: Name of the ECS Cluster in which the Task should be triggered.
  ECSSubnetName:
    Type: AWS::EC2::Subnet::Id
    Description: Name of the subnet in which the ECS Task should be triggered.
  ECSSecurityGroupName:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Name of the security group to use for the task.
  ParentStackName:
    Type: String
    Description: Name of the parent stack
  Workload:
    Type: String
    Description: Name of workload for this stack.
  EbsStorageMountPath:
    Type: String
    Description: Mount path for EBS storage
  WaiterDelay:
    Type: String
    Description: Time to wait before retrying service command in seconds
    Default: 5
  WaiterMaxAttempts:
    Type: String
    Description: Maximum number of retry attempts for service command
    Default: 30
  ExpansionRatio:
    Type: String
    Description: Ratio at which expanded packages are expected to increase
    Default: 3.5

Resources:
  UploadBucket:
    Type: AWS::S3::Bucket
    Properties:
      Tags:
        - Key: Environment
          Value: !Ref ApplicationEnvironment
        - Key: Application
          Value: !Ref ApplicationName
        - Key: Workload
          Value: !Ref Workload
        - Key: WorkloadType
          Value: processing
      BucketName: !Sub rac-${ApplicationEnvironment}-image-upload
      NotificationConfiguration:
        LambdaConfigurations:
          - Function: !GetAtt DigitizedImageTriggerFunction.Arn
            Event: 's3:ObjectCreated:*'
      PublicAccessBlockConfiguration: 
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
  
  UploadBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref UploadBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action: s3:ListBucket
            Resource: !GetAtt UploadBucket.Arn
            Principal:
              AWS:
                - 'arn:aws:iam::562779183889:user/rac-upload-user' # Crowley
                - 'arn:aws:iam::034638293334:user/NEDCC-Imaging' # NEDCC
          - Effect: Allow
            Action:
              - s3:GetObject
              - s3:PutObject
            Resource: !Sub 'arn:aws:s3:::${UploadBucket}/*'
            Principal:
              AWS:
                - 'arn:aws:iam::562779183889:user/rac-upload-user' # Crowley
                - 'arn:aws:iam::034638293334:user/NEDCC-Imaging' # NEDCC

  EcsInfrastructureRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSInfrastructureRolePolicyForVolumes

  DigitizedImageTriggerFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      Tags:
        - Key: Environment
          Value: !Ref ApplicationEnvironment
        - Key: Application
          Value: !Ref ApplicationName
        - Key: Workload
          Value: !Ref Workload
        - Key: WorkloadType
          Value: processing
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Description: IAM Role which supports running ECS Tasks and Services.
      Policies: 
        - PolicyName: DigitizedImageRunECSTaskPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 'ecs:RunTask'
                Resource: !Sub 'arn:aws:ecs:${AWS::Region}:${AWS::AccountId}:task-definition/digitized_image_*'
              - Effect: Allow
                Action: 
                  - 'ecs:DescribeServices'
                  - 'ecs:UpdateService'
                Resource: !Sub 'arn:aws:ecs:${AWS::Region}:${AWS::AccountId}:service/${ECSClusterName}/*'
              - Effect: Allow
                Action: 'iam:PassRole'
                Resource: !Sub 'arn:aws:iam::${AWS::AccountId}:role/${ParentStackName}-*'
                Condition:
                  StringLike:
                    'iam:PassedToService': 'ecs-tasks.amazonaws.com'
              - Effect: Allow
                Action: 
                  - 'ecs:ListTasks'
                Resource: !Sub 'arn:aws:ecs:${AWS::Region}:${AWS::AccountId}:container-instance/${ECSClusterName}/*'
              - Effect: Allow
                Action: 'ecs:ExecuteCommand'
                Resource: 
                  - !Sub arn:aws:ecs:${AWS::Region}:${AWS::AccountId}:cluster/${ECSClusterName}
                  - !Sub arn:aws:ecs:${AWS::Region}:${AWS::AccountId}:task/${ECSClusterName}/*
        - PolicyName: DigitizedImageParameterStorePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 
                  - 'ssm:GetParametersByPath*'
                Resource: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${ApplicationEnvironment}/${ApplicationName}*'
        - PolicyName: DigitizedImageLogPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: !GetAtt TriggerLogGroup.Arn
        - PolicyName: PassEcsInfrastructureRole
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 
                  - 'iam:PassRole'
                Resource: !GetAtt EcsInfrastructureRole.Arn
                Condition:
                  StringEquals:
                    iam:PassedToService: ecs.amazonaws.com

  ECSClusterParam:
    Type: AWS::SSM::Parameter
    Properties: 
      AllowedPattern: "^[A-Za-z0-9\\-\\_]+$"
      Description: Name of ECS Cluster in which Task should be triggered.
      Name: !Sub /${ApplicationEnvironment}/${ApplicationName}/ECS_CLUSTER
      Tags: 
        Environment: !Ref ApplicationEnvironment
        Application: !Ref ApplicationName
        Workload: !Ref Workload
        WorkloadType: processing
      Type: String
      Value: !Ref ECSClusterName
  ECSSubnetParam:
    Type: AWS::SSM::Parameter
    Properties: 
      AllowedPattern: "^[A-Za-z0-9\\-\\_]+$"
      Description: Subnet in which ECS Task should be triggered.
      Name: !Sub /${ApplicationEnvironment}/${ApplicationName}/ECS_SUBNET
      Tags: 
        Environment: !Ref ApplicationEnvironment
        Application: !Ref ApplicationName
        Workload: !Ref Workload
        WorkloadType: processing
      Type: String
      Value: !Ref ECSSubnetName
  ECSSecurityGroupParam:
    Type: AWS::SSM::Parameter
    Properties: 
      AllowedPattern: "^[A-Za-z0-9\\-\\_]+$"
      Description: Security group for the task.
      Name: !Sub /${ApplicationEnvironment}/${ApplicationName}/ECS_SECURITY_GROUP
      Tags: 
        Environment: !Ref ApplicationEnvironment
        Application: !Ref ApplicationName
        Workload: !Ref Workload
        WorkloadType: processing
      Type: String
      Value: !Ref ECSSecurityGroupName
  QCECSServiceParam:
    Type: AWS::SSM::Parameter
    Properties: 
      AllowedPattern: "^[A-Za-z0-9\\-\\_]+$"
      Description: QC Service which runs in ECS.
      Name: !Sub /${ApplicationEnvironment}/${ApplicationName}/QC_ECS_SERVICE
      Tags: 
        Environment: !Ref ApplicationEnvironment
        Application: !Ref ApplicationName
        Workload: !Ref Workload
        WorkloadType: processing
      Type: String
      Value: !ImportValue DigitizedImage-QcEcsServiceName
  WaiterDelayParam:
    Type: AWS::SSM::Parameter
    Properties: 
      Description: Time to delay before retrying waiter in seconds
      Name: !Sub /${ApplicationEnvironment}/${ApplicationName}/WAIT_DELAY
      Tags: 
        Environment: !Ref ApplicationEnvironment
        Application: !Ref ApplicationName
        Workload: !Ref Workload
        WorkloadType: processing
      Type: String
      Value: !Ref WaiterDelay
  WaiterMaxAttemptsParam:
    Type: AWS::SSM::Parameter
    Properties: 
      Description: Maximum retry attempts for waiter
      Name: !Sub /${ApplicationEnvironment}/${ApplicationName}/WAIT_MAX_ATTEMPTS
      Tags: 
        Environment: !Ref ApplicationEnvironment
        Application: !Ref ApplicationName
        Workload: !Ref Workload
        WorkloadType: processing
      Type: String
      Value: !Ref WaiterMaxAttempts
  ExpansionRatioParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: Ratio at which uncompressed packages expand
      Name: !Sub /${ApplicationEnvironment}/${ApplicationName}/EXPANSION_RATIO
      Tags: 
        Environment: !Ref ApplicationEnvironment
        Application: !Ref ApplicationName
        Workload: !Ref Workload
        WorkloadType: processing
      Type: String
      Value: !Ref ExpansionRatio
  EbsStorageMountPathParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: Mount path for EBS storage
      Name: !Sub /${ApplicationEnvironment}/${ApplicationName}/EBS_STORAGE_MOUNT_PATH
      Tags: 
        Environment: !Ref ApplicationEnvironment
        Application: !Ref ApplicationName
        Workload: !Ref Workload
        WorkloadType: processing
      Type: String
      Value: !Ref EbsStorageMountPath
  EbsVolumeRole:
    Type: AWS::SSM::Parameter
    Properties:
      Description: IAM role which allows ECS to configure volumes
      Name: !Sub /${ApplicationEnvironment}/${ApplicationName}/EBS_VOLUME_ROLE
      Tags: 
        Environment: !Ref ApplicationEnvironment
        Application: !Ref ApplicationName
        Workload: !Ref Workload
        WorkloadType: processing
      Type: String
      Value: !GetAtt EcsInfrastructureRole.Arn
  
  
  DigitizedImageTriggerFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Sub 'rac-${ApplicationEnvironment}-lambda'
        S3Key: !Sub '${ApplicationName}.zip'
      FunctionName: !Ref ApplicationName
      Handler: handle_digitized_image_trigger.lambda_handler
      LoggingConfig:
        LogGroup: !Ref TriggerLogGroup
      Role: !GetAtt DigitizedImageTriggerFunctionRole.Arn
      Runtime: python3.11
      Timeout: 120
      Environment:
        Variables:
          ENV:
            Ref: ApplicationEnvironment
          APP_CONFIG_PATH:
            Ref: ApplicationName
      Architectures:
        - x86_64
      Tags: 
        - Key: Environment
          Value: !Ref ApplicationEnvironment
        - Key: Application
          Value: !Ref ApplicationName
        - Key: Workload
          Value: !Ref Workload
        - Key: WorkloadType
          Value: processing

  TriggerLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${ApplicationName}"
      RetentionInDays: 90
      Tags: 
        - Key: Environment
          Value: !Ref ApplicationEnvironment
        - Key: Application
          Value: !Ref ApplicationName
        - Key: Workload
          Value: !Ref Workload
        - Key: WorkloadType
          Value: processing

  # Allow S3 to trigger Lambda
  DigitizedImageTriggerS3FunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref DigitizedImageTriggerFunction
      Principal: s3.amazonaws.com
      SourceArn: !Sub arn:aws:s3:::rac-${ApplicationEnvironment}-image-upload
      SourceAccount: !Ref AWS::AccountId

  # Allow SNS to trigger Lambda
  DigitizedImageTriggerSNSFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref DigitizedImageTriggerFunction
      Principal: sns.amazonaws.com
      SourceArn: !ImportValue DigitizedImage-SNSTopicArn
  
  # Subscribe Lambda to SNS
  DigitizedImageTriggerFunctionDigitizedImageEvents:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !GetAtt DigitizedImageTriggerFunction.Arn
      Protocol: lambda
      TopicArn: !ImportValue DigitizedImage-SNSTopicArn

Outputs:
  DigitizedImageTriggerFunction:
    Description: "Digitized Image Trigger Lambda Function ARN"
    Value: !GetAtt DigitizedImageTriggerFunction.Arn
    Export:
      Name: DigitizedImage-TriggerArn
