AWSTemplateFormatVersion: '2010-09-09'
Description: >
  digitized-image-validation

  Handles validation of incoming digitized still image and textual assets.

Parameters:
  ContainerAccountId:
    Type: String
    Description: Account ID under which container repository is located.
    Default: '817658541382'
  ApplicationEnvironment:
    Type: String
    Description: Environment in which application should be deployed.
    AllowedValues:
      - dev
      - prod
  ApplicationName:
    Type: String
    Description: Name of the application to be deployed.
  EfsId:
    Type: String
    Description: Identifier for temporary storage EFS.
  EfsAccessPointId:
    Type: String
    Description: Identifier for temporary storage EFS access point.
  EfsRootPath:
    Type: String
    Description: Root path at which EFS is mounted.
  StoragePath:
    Type: String
    Description: Temporary storage path into which files are moved during processing.
  DestinationBucketName:
    Type: String
    Description: Name of bucket to which valid files are moved after processing.
  Workload:
    Type: String
    Description: Name of workload for this stack.

Resources:
  ECSTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      Tags:
        - Key: Environment
          Value: !Ref ApplicationEnvironment
        - Key: Application
          Value: !Ref ApplicationName
        - Key: Workload
          Value: !Ref Workload
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: LogPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: 
                  - !GetAtt ValidationLogGroup.Arn
        - PolicyName: EcrPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 
                  - 'ecr:BatchCheckLayerAvailability'
                  - 'ecr:GetDownloadUrlForLayer'
                  - 'ecr:BatchGetImage'
                Resource: 
                  - !Sub arn:aws:ecr:${AWS::Region}:${ContainerAccountId}:repository/${ApplicationName}
              - Effect: Allow
                Action:
                  - 'ecr:GetAuthorizationToken'
                Resource: "*"

  DigitizedImageValidationUser:
    Type: AWS::IAM::User
    Properties:
      Tags:
        - Key: Environment
          Value: !Ref ApplicationEnvironment
        - Key: Application
          Value: !Ref ApplicationName
        - Key: Workload
          Value: !Ref Workload

  DigitizedImageValidationUserAccessKey:
    Type: AWS::IAM::AccessKey
    Properties: 
      UserName: !Ref DigitizedImageValidationUser

  DigitizedImageValidationS3Role:
    Type: AWS::IAM::Role
    Properties: 
      Tags:
        - Key: Environment
          Value: !Ref ApplicationEnvironment
        - Key: Application
          Value: !Ref ApplicationName
        - Key: Workload
          Value: !Ref Workload
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: 
              AWS:
                - !GetAtt DigitizedImageValidationUser.Arn
            Action:
              - 'sts:AssumeRole'
      Description: 'Allows management of S3 assets.'
      Policies:
        - PolicyName: DigitizedImageValidationS3BucketPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 
                  - 's3:ListBucket'
                Resource: 
                  - !Sub arn:aws:s3:::rac-${ApplicationEnvironment}-image-upload
                  - !Sub arn:aws:s3:::${DestinationBucketName}
        - PolicyName: DigitizedImageValidationS3ObjectPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 
                  - 's3:GetObject'
                  - 's3:DeleteObject'
                  - 's3:PutObject'
                Resource: 
                  - !Sub arn:aws:s3:::rac-${ApplicationEnvironment}-image-upload/*
                  - !Sub arn:aws:s3:::${DestinationBucketName}/*
  
  DigitizedImageValidationSnsRole:
    Type: AWS::IAM::Role
    Properties: 
      Tags:
        - Key: Environment
          Value: !Ref ApplicationEnvironment
        - Key: Application
          Value: !Ref ApplicationName
        - Key: Workload
          Value: !Ref Workload
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: 
              AWS:
                - !GetAtt DigitizedImageValidationUser.Arn
            Action:
              - 'sts:AssumeRole'
      Description: 'Allows creation of SNS messages.'
      Policies:      
        - PolicyName: DigitizedImageValidationSNSPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 'sns:Publish'
                Resource: !ImportValue DigitizedImage-SNSTopicArn

  ValidationLogGroup:
    Type: AWS::Logs::LogGroup
    Properties: 
      LogGroupName: !Sub "/digitized_image/ecs/${ApplicationName}"
      RetentionInDays: 90
      Tags:
        - Key: Environment
          Value: !Ref ApplicationEnvironment
        - Key: Application
          Value: !Ref ApplicationName
        - Key: Workload
          Value: !Ref Workload

  ValidationECSTask:
    Type: AWS::ECS::TaskDefinition
    Properties: 
      Cpu: "1024"
      Memory: "3072"
      ContainerDefinitions: 
        - Name: !Ref ApplicationName
          Image: !Sub "${ContainerAccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ApplicationName}:${ApplicationEnvironment}"
          Essential: true
          Environment:
            - Name: AWS_ACCESS_KEY_ID
              Value: !Ref DigitizedImageValidationUserAccessKey
            - Name: AWS_SECRET_ACCESS_KEY
              Value: !GetAtt DigitizedImageValidationUserAccessKey.SecretAccessKey
            - Name: AWS_S3_ROLE_ARN
              Value: !GetAtt DigitizedImageValidationS3Role.Arn
            - Name: AWS_SNS_ROLE_ARN
              Value: !GetAtt DigitizedImageValidationSnsRole.Arn
            - Name: ENV
              Value: !Ref ApplicationEnvironment
            - Name: APP_CONFIG_PATH
              Value: !Ref ApplicationName
            - Name: TMP_DIR
              Value: !Sub '${EfsRootPath}/${StoragePath}'
            - Name: DESTINATION_BUCKET
              Value: !Ref DestinationBucketName
            - Name: AWS_REGION_NAME
              Value: !Ref AWS::Region
            - Name: AWS_SNS_TOPIC
              Value: !ImportValue DigitizedImage-SNSTopicArn
          MountPoints:
            - SourceVolume: efs
              ContainerPath: !Ref EfsRootPath
              ReadOnly: false
          ReadonlyRootFilesystem: true
          LogConfiguration:
            LogDriver: awslogs
            Options:
              "awslogs-group": !Ref ValidationLogGroup
              "awslogs-region": "us-east-1"
              "awslogs-stream-prefix": "ecs"
      ExecutionRoleArn: !GetAtt ECSTaskExecutionRole.Arn
      Family: !Ref ApplicationName
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      RuntimePlatform:
        CpuArchitecture: X86_64
        OperatingSystemFamily: LINUX
      Tags:
        - Key: Environment
          Value: !Ref ApplicationEnvironment
        - Key: Application
          Value: !Ref ApplicationName
        - Key: Workload
          Value: !Ref Workload
      Volumes: 
        - Name: efs
          EFSVolumeConfiguration:
            FilesystemId: !Ref EfsId
            RootDirectory: /
            TransitEncryption: ENABLED
            AuthorizationConfig:
              AccessPointId: !Ref EfsAccessPointId
              IAM: DISABLED

Outputs:
  ValidationECSTask:
    Description: "Validation ECS Task Definition ARN"
    Value: !Ref ValidationECSTask