AWSTemplateFormatVersion: '2010-09-09'
Description: >
  digitized-image-validation

  Handles validation of incoming digitized still image and textual assets.

Parameters:
  ContainerAccountId:
    Type: String
    Description: Account ID under which container repository is located.
    Default: '817658541382'
  ApplicationEnvironment:
    Type: String
    Description: Environment in which application should be deployed.
    AllowedValues:
      - dev
      - prod
  ApplicationName:
    Type: String
    Description: Name of the application to be deployed.
  EfsId:
    Type: String
    Description: Identifier for temporary storage EFS.
  EfsAccessPointId:
    Type: String
    Description: Identifier for temporary storage EFS access point.
  EfsRootPath:
    Type: String
    Description: Root path at which EFS is mounted.
  StoragePath:
    Type: String
    Description: Temporary storage path into which files are moved during processing.
  DestinationPath:
    Type: String
    Description: Destination storage path to which valid files are moved after processing.

Resources:
  ECSTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      Policies:
        - PolicyName: CreateLogGroupPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 
                  - 'logs:CreateLogGroup'
                Resource: 
                  - '*'

  DigitizedImageValidationUser:
    Type: AWS::IAM::User

  DigitizedImageValidationUserAccessKey:
    Type: AWS::IAM::AccessKey
    Properties: 
      UserName: !Ref DigitizedImageValidationUser

  DigitizedImageValidationRole:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: 
              AWS:
                - !GetAtt DigitizedImageValidationUser.Arn
            Action:
              - 'sts:AssumeRole'
      Description: !Sub 'Allows management of S3 assets and creation of SNS messages.'
      Policies:
        - PolicyName: DigitizedImageValidationS3BucketPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 
                  - 's3:ListBucket'
                Resource: 
                  - !GetAtt UploadBucket.Arn
        - PolicyName: DigitizedImageValidationS3ObjectPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 
                  - 's3:GetObject'
                  - 's3:DeleteObject'
                Resource: 
                  - !Sub '${UploadBucket.Arn}/*'
        - PolicyName: DigitizedImageValidationSNSPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 'sns:Publish'
                Resource: !ImportValue DigitizedImage-SNSTopicArn

  ValidationLogGroup:
    Type: AWS::Logs::LogGroup
    Properties: 
      LogGroupName: !Sub "/digitized_image/ecs/${ApplicationName}"
      RetentionInDays: 90

  ValidationECSTask:
    Type: AWS::ECS::TaskDefinition
    Properties: 
      Cpu: "1024"
      Memory: "3072"
      ContainerDefinitions: 
        - Name: !Ref ApplicationName
          Image: !Sub "${ContainerAccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ApplicationName}:latest"
          Essential: true
          Environment:
            - Name: AWS_ACCESS_KEY_ID
              Value: !Ref DigitizedImageValidationUserAccessKey
            - Name: AWS_SECRET_ACCESS_KEY
              Value: !GetAtt DigitizedImageValidationUserAccessKey.SecretAccessKey
            - Name: AWS_ROLE_ARN
              Value: !GetAtt DigitizedImageValidationRole.Arn
            - Name: ENV
              Value: !Ref ApplicationEnvironment
            - Name: APP_CONFIG_PATH
              Value: !Ref ApplicationName
            - Name: TMP_DIR
              Value: !Sub '${EfsRootPath}/${StoragePath}'
            - Name: DESTINATION_DIR
              Value: !Sub '${EfsRootPath}/${DestinationPath}'
            - Name: AWS_REGION_NAME
              Value: !Ref AWS::Region
            - Name: AWS_SNS_TOPIC
              Value: !ImportValue DigitizedImage-SNSTopicArn
          MountPoints:
            - SourceVolume: efs
              ContainerPath: !Ref EfsRootPath
              ReadOnly: false
          LogConfiguration:
            LogDriver: awslogs
            Options:
              "awslogs-group": !Ref ValidationLogGroup
              "awslogs-region": "us-east-1"
              "awslogs-stream-prefix": "ecs"
      ExecutionRoleArn: !GetAtt ECSTaskExecutionRole.Arn
      Family: !Ref ApplicationName
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      RuntimePlatform:
        CpuArchitecture: X86_64
        OperatingSystemFamily: LINUX
      Volumes: 
        - Name: efs
          EFSVolumeConfiguration:
            FilesystemId: !Ref EfsId
            RootDirectory: /
            TransitEncryption: ENABLED
            AuthorizationConfig:
              AccessPointId: !Ref EfsAccessPointId
              IAM: DISABLED
  
  UploadBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub rac-${ApplicationEnvironment}-image-upload
      NotificationConfiguration:
        LambdaConfigurations:
          - Function: !ImportValue DigitizedImage-TriggerArn
            Event: 's3:ObjectCreated:*'
      PublicAccessBlockConfiguration: 
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

Outputs:
  ValidationECSTask:
    Description: "Validation ECS Task Definition ARN"
    Value: !Ref ValidationECSTask
  UploadBucket:
    Description: "Upload S3 bucket ARN"
    Value: !GetAtt UploadBucket.Arn
