name: Push to S3

on:
  push:
    branches:
      - base
      - development

jobs:
  push:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: ${{ secrets.AWS_S3_ROLE }}
          aws-region: us-east-1
          role-skip-session-tagging: true

      - name: Sync to AWS
        run: |
          aws s3 sync . s3://${{ secrets.S3_BUCKET_NAME }}/digitized_image_pipeline \
            --exclude "*" \
            --include "*.yaml"
